<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'messenger.bus.default.middleware.handle_message' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Handler/HandlersLocator.php';

$this->privates['messenger.bus.default.middleware.handle_message'] = $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator([]));

$instance->setLogger(($this->privates['monolog.logger.messenger'] ?? $this->load('getMonolog_Logger_MessengerService.php')));

return $instance;
