<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Photo\PhotoPonkaficator' shared autowired service.

include_once $this->targetDirs[3].'/src/Photo/PhotoPonkaficator.php';
include_once $this->targetDirs[3].'/vendor/intervention/image/src/Intervention/Image/ImageManager.php';

return $this->privates['App\\Photo\\PhotoPonkaficator'] = new \App\Photo\PhotoPonkaficator(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), new \Intervention\Image\ImageManager(), ($this->privates['photo.filesystem'] ?? $this->load('getPhoto_FilesystemService.php')));
