<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8JYzEIk\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8JYzEIk/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/Container8JYzEIk.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\Container8JYzEIk\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \Container8JYzEIk\srcApp_KernelProdContainer([
    'container.build_hash' => '8JYzEIk',
    'container.build_id' => 'c892e7c6',
    'container.build_time' => 1637747068,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8JYzEIk');
