<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_imagepost_list' => [[], ['_controller' => 'App\\Controller\\ImagePostController::list'], [], [['text', '/api/images']], [], []],
    'app_imagepost_create' => [[], ['_controller' => 'App\\Controller\\ImagePostController::create'], [], [['text', '/api/images']], [], []],
    'app_imagepost_delete' => [['id'], ['_controller' => 'App\\Controller\\ImagePostController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/images']], [], []],
    'get_image_post_item' => [['id'], ['_controller' => 'App\\Controller\\ImagePostController::getItem'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/images']], [], []],
    'app_main_homepage' => [[], ['_controller' => 'App\\Controller\\MainController::homepage'], [], [['text', '/']], [], []],
];
