<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.messenger.handler_descriptor.v9ouAGu' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
include_once $this->targetDirs[3].'/src/MessageHandler/DeletePhotoFIleHandler.php';

return $this->privates['.messenger.handler_descriptor.v9ouAGu'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\MessageHandler\DeletePhotoFIleHandler(($this->privates['App\\Photo\\PhotoFileManager'] ?? $this->load('getPhotoFileManagerService.php'))), []);
