<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.messenger.handler_descriptor.PDdrsmA' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
include_once $this->targetDirs[3].'/vendor/psr/log/Psr/Log/LoggerAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/psr/log/Psr/Log/LoggerAwareTrait.php';
include_once $this->targetDirs[3].'/src/MessageHandler/AddPonkaToImageHandler.php';
include_once $this->targetDirs[3].'/src/Photo/PhotoPonkaficator.php';
include_once $this->targetDirs[3].'/vendor/intervention/image/src/Intervention/Image/ImageManager.php';

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));

$b = new \App\MessageHandler\AddPonkaToImageHandler(new \App\Photo\PhotoPonkaficator($a, new \Intervention\Image\ImageManager(), ($this->privates['photo.filesystem'] ?? $this->load('getPhoto_FilesystemService.php'))), ($this->privates['App\\Photo\\PhotoFileManager'] ?? $this->load('getPhotoFileManagerService.php')), $a, ($this->privates['App\\Repository\\ImagePostRepository'] ?? $this->load('getImagePostRepositoryService.php')));
$b->setLogger(($this->privates['monolog.logger'] ?? $this->load('getMonolog_LoggerService.php')));

return $this->privates['.messenger.handler_descriptor.PDdrsmA'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor($b, []);
