<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'messenger.transport.async_priority_high' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/Receiver/ReceiverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/Sender/SenderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/TransportInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/Serialization/SerializerInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/Serialization/PhpSerializer.php';

return $this->privates['messenger.transport.async_priority_high'] = ($this->privates['messenger.transport_factory'] ?? $this->load('getMessenger_TransportFactoryService.php'))->createTransport($this->getEnv('MESSENGER_TRANSPORT_DSN'), ['queue_name' => 'high'], ($this->privates['messenger.transport.native_php_serializer'] ?? ($this->privates['messenger.transport.native_php_serializer'] = new \Symfony\Component\Messenger\Transport\Serialization\PhpSerializer())));
