<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'services_resetter' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/DependencyInjection/ServicesResetter.php';

return $this->services['services_resetter'] = new \Symfony\Component\HttpKernel\DependencyInjection\ServicesResetter(new RewindableGenerator(function () {
    if (isset($this->privates['messenger.transport.in_memory.factory'])) {
        yield 'messenger.transport.in_memory.factory' => ($this->privates['messenger.transport.in_memory.factory'] ?? null);
    }
    if (isset($this->privates['debug.stopwatch'])) {
        yield 'debug.stopwatch' => ($this->privates['debug.stopwatch'] ?? null);
    }
    if (isset($this->privates['monolog.handler.main'])) {
        yield 'monolog.handler.main' => ($this->privates['monolog.handler.main'] ?? null);
    }
    if (isset($this->privates['monolog.handler.messenger'])) {
        yield 'monolog.handler.messenger' => ($this->privates['monolog.handler.messenger'] ?? null);
    }
    if (isset($this->privates['monolog.handler.console'])) {
        yield 'monolog.handler.console' => ($this->privates['monolog.handler.console'] ?? null);
    }
    if (isset($this->privates['monolog.handler.deprecation'])) {
        yield 'monolog.handler.deprecation' => ($this->privates['monolog.handler.deprecation'] ?? null);
    }
    if (isset($this->privates['monolog.handler.deprecation_filter'])) {
        yield 'monolog.handler.deprecation_filter' => ($this->privates['monolog.handler.deprecation_filter'] ?? null);
    }
    if (isset($this->privates['webpack_encore.tag_renderer'])) {
        yield 'webpack_encore.tag_renderer' => ($this->privates['webpack_encore.tag_renderer'] ?? null);
    }
    if (isset($this->privates['webpack_encore.entrypoint_lookup[_default]'])) {
        yield 'webpack_encore.entrypoint_lookup[_default]' => ($this->privates['webpack_encore.entrypoint_lookup[_default]'] ?? null);
    }
}, function () {
    return 0 + (int) (isset($this->privates['messenger.transport.in_memory.factory'])) + (int) (isset($this->privates['debug.stopwatch'])) + (int) (isset($this->privates['monolog.handler.main'])) + (int) (isset($this->privates['monolog.handler.messenger'])) + (int) (isset($this->privates['monolog.handler.console'])) + (int) (isset($this->privates['monolog.handler.deprecation'])) + (int) (isset($this->privates['monolog.handler.deprecation_filter'])) + (int) (isset($this->privates['webpack_encore.tag_renderer'])) + (int) (isset($this->privates['webpack_encore.entrypoint_lookup[_default]']));
}), ['messenger.transport.in_memory.factory' => 'reset', 'debug.stopwatch' => 'reset', 'monolog.handler.main' => 'reset', 'monolog.handler.messenger' => 'reset', 'monolog.handler.console' => 'reset', 'monolog.handler.deprecation' => 'reset', 'monolog.handler.deprecation_filter' => 'reset', 'webpack_encore.tag_renderer' => 'reset', 'webpack_encore.entrypoint_lookup[_default]' => 'reset']);
