<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.JJpJxwc' shared service.

return $this->privates['.service_locator.JJpJxwc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'imagePost' => ['privates', '.errored..service_locator.JJpJxwc.App\\Entity\\ImagePost', NULL, 'Cannot autowire service ".service_locator.JJpJxwc": it references class "App\\Entity\\ImagePost" but no such service exists.'],
    'photoManager' => ['privates', 'App\\Photo\\PhotoFileManager', 'getPhotoFileManagerService.php', true],
], [
    'entityManager' => '?',
    'imagePost' => 'App\\Entity\\ImagePost',
    'photoManager' => 'App\\Photo\\PhotoFileManager',
]);
