<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BECuMFQ' shared service.

return $this->privates['.service_locator.BECuMFQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'photoManager' => ['privates', 'App\\Photo\\PhotoFileManager', 'getPhotoFileManagerService.php', true],
    'ponkaficator' => ['privates', 'App\\Photo\\PhotoPonkaficator', 'getPhotoPonkaficatorService.php', true],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'entityManager' => '?',
    'photoManager' => 'App\\Photo\\PhotoFileManager',
    'ponkaficator' => 'App\\Photo\\PhotoPonkaficator',
    'validator' => '?',
]);
