<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Messenger\AuditMiddleware' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
include_once $this->targetDirs[3].'/src/Messenger/AuditMiddleware.php';

return $this->privates['App\\Messenger\\AuditMiddleware'] = new \App\Messenger\AuditMiddleware(($this->services['monolog.logger.messenger_audit'] ?? $this->load('getMonolog_Logger_MessengerAuditService.php')));
