<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'messenger.failure.send_failed_message_to_failure_transport_listener' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/messenger/EventListener/SendFailedMessageToFailureTransportListener.php';

return $this->privates['messenger.failure.send_failed_message_to_failure_transport_listener'] = new \Symfony\Component\Messenger\EventListener\SendFailedMessageToFailureTransportListener(($this->privates['messenger.routable_message_bus'] ?? $this->load('getMessenger_RoutableMessageBusService.php')), 'failed', ($this->privates['monolog.logger.messenger'] ?? $this->load('getMonolog_Logger_MessengerService.php')));
