<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNiiTExT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNiiTExT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNiiTExT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNiiTExT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNiiTExT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NiiTExT',
    'container.build_id' => '0dc834ab',
    'container.build_time' => 1637747177,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNiiTExT');
