<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRRaRjt8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRRaRjt8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRRaRjt8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRRaRjt8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRRaRjt8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RRaRjt8',
    'container.build_id' => 'fadeeed3',
    'container.build_time' => 1637666752,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRRaRjt8');
